// Package toolinjection provides a framework for injecting tool calls into proxy responses.
// It intercepts requests, fabricates tool_call responses for the client to execute,
// then strips the injected messages before forwarding to the upstream provider.
package toolinjection

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"strconv"
	"strings"

	"github.com/router-for-me/CLIProxyAPI/v6/internal/config"
	"github.com/tidwall/gjson"
)

// InjectedIDMarker is embedded in all generated tool call IDs so they can be
// recognised and stripped from follow-up requests.
const InjectedIDMarker = "cpa_inject_"

// GenerateOpenAIToolCallID returns an ID of the form "call_cpa_inject_<8hex taskID><8hex random>".
// The taskID is encoded so it can be extracted from captured results.
func GenerateOpenAIToolCallID(taskID uint32) string {
	return "call_" + InjectedIDMarker + encodeTaskID(taskID) + randomHex(8)
}

// GenerateClaudeToolUseID returns an ID of the form "toolu_cpa_inject_<8hex taskID><8hex random>".
func GenerateClaudeToolUseID(taskID uint32) string {
	return "toolu_" + InjectedIDMarker + encodeTaskID(taskID) + randomHex(8)
}

// IsInjectedID reports whether the given ID was generated by this package.
func IsInjectedID(id string) bool {
	return strings.Contains(id, InjectedIDMarker)
}

// ExtractTaskID extracts the encoded task ID from an injected call ID.
// Returns (taskID, true) on success or (0, false) if the ID is not injected
// or cannot be parsed.
func ExtractTaskID(callID string) (uint32, bool) {
	idx := strings.Index(callID, InjectedIDMarker)
	if idx < 0 {
		return 0, false
	}
	hex8 := callID[idx+len(InjectedIDMarker):]
	if len(hex8) < 8 {
		return 0, false
	}
	val, err := strconv.ParseUint(hex8[:8], 16, 32)
	if err != nil {
		return 0, false
	}
	return uint32(val), true
}

// encodeTaskID encodes a task ID as 8 hex characters.
func encodeTaskID(taskID uint32) string {
	return fmt.Sprintf("%08x", taskID)
}

// ShouldInject checks the request's tools array against the configured injection rules
// and returns the first matching enabled rule, or nil if none match.
//
// format must be "openai" or "claude".
func ShouldInject(rawJSON []byte, rules []config.ToolCallInjectionRule, modelName, format string) *config.ToolCallInjectionRule {
	if len(rules) == 0 {
		return nil
	}

	// Collect tool names from the request.
	toolNames := collectToolNames(rawJSON, format)
	if len(toolNames) == 0 {
		return nil
	}

	for i := range rules {
		rule := &rules[i]
		if !rule.Enabled {
			continue
		}
		if _, ok := toolNames[rule.ToolName]; !ok {
			continue
		}
		// Check model pattern.
		if rule.ModelPattern != "" && !matchModelPattern(rule.ModelPattern, modelName) {
			continue
		}
		// Check max injections.
		maxInj := rule.MaxInjections
		if maxInj <= 0 {
			maxInj = 1 // default: inject once
		}
		if countExistingInjections(rawJSON, format) >= maxInj {
			continue
		}
		return rule
	}
	return nil
}

// collectToolNames returns a set of tool function names present in the request.
func collectToolNames(rawJSON []byte, format string) map[string]struct{} {
	names := make(map[string]struct{})
	tools := gjson.GetBytes(rawJSON, "tools")
	if !tools.Exists() || !tools.IsArray() {
		return names
	}
	tools.ForEach(func(_, tool gjson.Result) bool {
		var name string
		switch format {
		case "openai":
			name = tool.Get("function.name").String()
		case "openai-responses":
			// Responses API: {"type":"function","name":"...","parameters":{...}}
			name = tool.Get("name").String()
		default: // claude
			name = tool.Get("name").String()
		}
		if name != "" {
			names[name] = struct{}{}
		}
		return true
	})
	return names
}

// countExistingInjections counts how many injected tool call IDs already exist
// in the conversation messages.
func countExistingInjections(rawJSON []byte, format string) int {
	count := 0

	if format == "openai-responses" {
		// Responses API uses "input" array with {"type":"function_call","call_id":"..."}
		input := gjson.GetBytes(rawJSON, "input")
		if !input.Exists() || !input.IsArray() {
			return 0
		}
		input.ForEach(func(_, item gjson.Result) bool {
			if item.Get("type").String() == "function_call" {
				if IsInjectedID(item.Get("call_id").String()) {
					count++
				}
			}
			return true
		})
		return count
	}

	messages := gjson.GetBytes(rawJSON, "messages")
	if !messages.Exists() || !messages.IsArray() {
		return 0
	}
	messages.ForEach(func(_, msg gjson.Result) bool {
		switch format {
		case "openai":
			// Check assistant messages with tool_calls
			msg.Get("tool_calls").ForEach(func(_, tc gjson.Result) bool {
				if IsInjectedID(tc.Get("id").String()) {
					count++
				}
				return true
			})
		default: // claude
			// Check content blocks with tool_use
			msg.Get("content").ForEach(func(_, block gjson.Result) bool {
				if block.Get("type").String() == "tool_use" && IsInjectedID(block.Get("id").String()) {
					count++
				}
				return true
			})
		}
		return true
	})
	return count
}

// matchModelPattern performs simple wildcard matching where '*' matches zero or more characters.
func matchModelPattern(pattern, model string) bool {
	pattern = strings.TrimSpace(pattern)
	model = strings.TrimSpace(model)
	if pattern == "" {
		return false
	}
	if pattern == "*" {
		return true
	}
	pi, si := 0, 0
	starIdx := -1
	matchIdx := 0
	for si < len(model) {
		if pi < len(pattern) && pattern[pi] == model[si] {
			pi++
			si++
		} else if pi < len(pattern) && pattern[pi] == '*' {
			starIdx = pi
			matchIdx = si
			pi++
		} else if starIdx >= 0 {
			pi = starIdx + 1
			matchIdx++
			si = matchIdx
		} else {
			return false
		}
	}
	for pi < len(pattern) && pattern[pi] == '*' {
		pi++
	}
	return pi == len(pattern)
}

// RemoveRuleByName removes the first rule with the given name from the slice
// and returns the resulting slice. Used to delete a rule after it fires.
func RemoveRuleByName(rules []config.ToolCallInjectionRule, name string) []config.ToolCallInjectionRule {
	for i, r := range rules {
		if r.Name == name {
			return append(rules[:i], rules[i+1:]...)
		}
	}
	return rules
}

func randomHex(n int) string {
	b := make([]byte, n)
	_, _ = rand.Read(b)
	return hex.EncodeToString(b)
}
